[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui_glow = "0.27.2"
glutin = "0.30"
glow_glyph = {git = "https://github.com/nmeylan/glow_glyph", rev = "8ef9138"}
glow = "0.13.1"
bytecount = "0.6.2"
elapsed-time = "0.1"
